version: "3"
services: 
    jenkins:
        image: jenkins/jenkins:lts
        ports: 
            - 8083:8080
            - 50000:50000
        volumes: 
            - jenkins-data:/var/jenkins_home
volumes: 
    jenkins-data:
        driver: local